// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_groupcond_logl
double compute_groupcond_logl(NumericMatrix x, NumericMatrix muy, NumericVector sigmayw, NumericMatrix muwz, NumericMatrix sigmaz, NumericVector ghweight, double detvarz, IntegerVector dims);
RcppExport SEXP _lavacreg_compute_groupcond_logl(SEXP xSEXP, SEXP muySEXP, SEXP sigmaywSEXP, SEXP muwzSEXP, SEXP sigmazSEXP, SEXP ghweightSEXP, SEXP detvarzSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type muy(muySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmayw(sigmaywSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type muwz(muwzSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigmaz(sigmazSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ghweight(ghweightSEXP);
    Rcpp::traits::input_parameter< double >::type detvarz(detvarzSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_groupcond_logl(x, muy, sigmayw, muwz, sigmaz, ghweight, detvarz, dims));
    return rcpp_result_gen;
END_RCPP
}
// creg_group_logl_cpp
NumericVector creg_group_logl_cpp(List datalist, List modellist);
RcppExport SEXP _lavacreg_creg_group_logl_cpp(SEXP datalistSEXP, SEXP modellistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< List >::type modellist(modellistSEXP);
    rcpp_result_gen = Rcpp::wrap(creg_group_logl_cpp(datalist, modellist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lavacreg_compute_groupcond_logl", (DL_FUNC) &_lavacreg_compute_groupcond_logl, 8},
    {"_lavacreg_creg_group_logl_cpp", (DL_FUNC) &_lavacreg_creg_group_logl_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lavacreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
