# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the group-conditional log-likelihood function
#' 
#' @param x Numeric matrix
#' @export
compute_groupcond_logl <- function(x, muy, sigmayw, muwz, sigmaz, ghweight, detvarz, dims) {
    .Call(`_CountReg_compute_groupcond_logl`, x, muy, sigmayw, muwz, sigmaz, ghweight, detvarz, dims)
}

rcpp_hello_world <- function() {
    .Call(`_CountReg_rcpp_hello_world`)
}

