# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the group-conditional log-likelihood function
#'
#' @param x Model matrix containing the observed variables in order Y, W, Z
#' @param muy Matrix of conditional expectations of Y given Z and/or latent
NULL

compute_groupcond_logl <- function(y, w, z, beta, Beta, gamma, Gamma, Omega, overdis, nu, Lambda, Theta, mu_eta, Sigma_eta, fixeta, ghweight, mu_z, Sigma_z, Sigma_z_lv, fixed_z, cores = 1L) {
    .Call('_lavacreg_compute_groupcond_logl', PACKAGE = 'lavacreg', y, w, z, beta, Beta, gamma, Gamma, Omega, overdis, nu, Lambda, Theta, mu_eta, Sigma_eta, fixeta, ghweight, mu_z, Sigma_z, Sigma_z_lv, fixed_z, cores)
}

